# Built-in fallback: ~500 iconic songs spanning decades and genres.
# Used only when no CSV or Last.fm key is configured.
TOP_500: list[tuple[str, str]] = [
    # ── Classic Rock ──────────────────────────────────────────────────────────
    ("Bohemian Rhapsody", "Queen"),
    ("Hotel California", "Eagles"),
    ("Stairway to Heaven", "Led Zeppelin"),
    ("Sweet Child O' Mine", "Guns N' Roses"),
    ("Smells Like Teen Spirit", "Nirvana"),
    ("Back in Black", "AC/DC"),
    ("Purple Haze", "Jimi Hendrix"),
    ("Johnny B. Goode", "Chuck Berry"),
    ("Born to Run", "Bruce Springsteen"),
    ("Light My Fire", "The Doors"),
    ("Satisfaction", "The Rolling Stones"),
    ("Gimme Shelter", "The Rolling Stones"),
    ("Layla", "Derek and the Dominos"),
    ("Black Dog", "Led Zeppelin"),
    ("Comfortably Numb", "Pink Floyd"),
    ("Another Brick in the Wall", "Pink Floyd"),
    ("Dream On", "Aerosmith"),
    ("Jump", "Van Halen"),
    ("Pour Some Sugar on Me", "Def Leppard"),
    ("Eye of the Tiger", "Survivor"),
    ("We Will Rock You", "Queen"),
    ("Don't Stop Me Now", "Queen"),
    ("Roxanne", "The Police"),
    ("Every Breath You Take", "The Police"),
    ("Message in a Bottle", "The Police"),
    ("Under Pressure", "Queen"),
    ("Space Oddity", "David Bowie"),
    ("Heroes", "David Bowie"),
    ("Life on Mars", "David Bowie"),
    ("Ziggy Stardust", "David Bowie"),
    # ── The Beatles / British Invasion ────────────────────────────────────────
    ("Hey Jude", "The Beatles"),
    ("Let It Be", "The Beatles"),
    ("Yesterday", "The Beatles"),
    ("Come Together", "The Beatles"),
    ("Blackbird", "The Beatles"),
    ("A Day in the Life", "The Beatles"),
    ("Lucy in the Sky with Diamonds", "The Beatles"),
    ("Something", "The Beatles"),
    ("Help!", "The Beatles"),
    ("Eleanor Rigby", "The Beatles"),
    ("Here Comes the Sun", "The Beatles"),
    ("Good Vibrations", "The Beach Boys"),
    ("God Only Knows", "The Beach Boys"),
    ("Waterloo Sunset", "The Kinks"),
    ("You Really Got Me", "The Kinks"),
    # ── Soul / R&B / Motown ───────────────────────────────────────────────────
    ("Respect", "Aretha Franklin"),
    ("A Change Is Gonna Come", "Sam Cooke"),
    ("What's Going On", "Marvin Gaye"),
    ("Let's Get It On", "Marvin Gaye"),
    ("Sexual Healing", "Marvin Gaye"),
    ("Superstition", "Stevie Wonder"),
    ("Isn't She Lovely", "Stevie Wonder"),
    ("Higher Ground", "Stevie Wonder"),
    ("Sir Duke", "Stevie Wonder"),
    ("Living for the City", "Stevie Wonder"),
    ("What'd I Say", "Ray Charles"),
    ("Hit the Road Jack", "Ray Charles"),
    ("Stand by Me", "Ben E. King"),
    ("Under the Boardwalk", "The Drifters"),
    ("My Girl", "The Temptations"),
    ("Ain't Too Proud to Beg", "The Temptations"),
    ("I Heard It Through the Grapevine", "Marvin Gaye"),
    ("Dancing in the Street", "Martha and the Vandellas"),
    ("Stop! In the Name of Love", "The Supremes"),
    ("I Want You Back", "The Jackson 5"),
    ("ABC", "The Jackson 5"),
    ("I'll Be There", "The Jackson 5"),
    ("Purple Rain", "Prince"),
    ("When Doves Cry", "Prince"),
    ("Kiss", "Prince"),
    ("Sign 'O' the Times", "Prince"),
    ("Crazy in Love", "Beyonce"),
    ("Single Ladies", "Beyonce"),
    ("Halo", "Beyonce"),
    ("Irreplaceable", "Beyonce"),
    ("Formation", "Beyonce"),
    # ── Pop ───────────────────────────────────────────────────────────────────
    ("Billie Jean", "Michael Jackson"),
    ("Beat It", "Michael Jackson"),
    ("Thriller", "Michael Jackson"),
    ("Man in the Mirror", "Michael Jackson"),
    ("Black or White", "Michael Jackson"),
    ("Bad", "Michael Jackson"),
    ("Smooth Criminal", "Michael Jackson"),
    ("Like a Prayer", "Madonna"),
    ("Material Girl", "Madonna"),
    ("Vogue", "Madonna"),
    ("Express Yourself", "Madonna"),
    ("Papa Don't Preach", "Madonna"),
    ("Born This Way", "Lady Gaga"),
    ("Bad Romance", "Lady Gaga"),
    ("Poker Face", "Lady Gaga"),
    ("Just Dance", "Lady Gaga"),
    ("Shallow", "Lady Gaga"),
    ("Rolling in the Deep", "Adele"),
    ("Someone Like You", "Adele"),
    ("Hello", "Adele"),
    ("Set Fire to the Rain", "Adele"),
    ("Skyfall", "Adele"),
    ("Shape of You", "Ed Sheeran"),
    ("Thinking Out Loud", "Ed Sheeran"),
    ("Perfect", "Ed Sheeran"),
    ("Photograph", "Ed Sheeran"),
    ("Bad Habits", "Ed Sheeran"),
    ("Stay With Me", "Sam Smith"),
    ("In the Lonely Hour", "Sam Smith"),
    ("Writing's on the Wall", "Sam Smith"),
    ("Unholy", "Sam Smith"),
    ("Watermelon Sugar", "Harry Styles"),
    ("As It Was", "Harry Styles"),
    ("Adore You", "Harry Styles"),
    ("Levitating", "Dua Lipa"),
    ("Don't Start Now", "Dua Lipa"),
    ("Physical", "Dua Lipa"),
    ("New Rules", "Dua Lipa"),
    ("drivers license", "Olivia Rodrigo"),
    ("good 4 u", "Olivia Rodrigo"),
    ("deja vu", "Olivia Rodrigo"),
    ("brutal", "Olivia Rodrigo"),
    ("Blinding Lights", "The Weeknd"),
    ("Starboy", "The Weeknd"),
    ("Can't Feel My Face", "The Weeknd"),
    ("The Hills", "The Weeknd"),
    ("Save Your Tears", "The Weeknd"),
    # ── Hip-Hop / Rap ─────────────────────────────────────────────────────────
    ("Lose Yourself", "Eminem"),
    ("Stan", "Eminem"),
    ("Without Me", "Eminem"),
    ("Slim Shady", "Eminem"),
    ("Rap God", "Eminem"),
    ("HUMBLE.", "Kendrick Lamar"),
    ("DNA.", "Kendrick Lamar"),
    ("Alright", "Kendrick Lamar"),
    ("Swimming Pools", "Kendrick Lamar"),
    ("Backseat Freestyle", "Kendrick Lamar"),
    ("God's Plan", "Drake"),
    ("One Dance", "Drake"),
    ("Hotline Bling", "Drake"),
    ("Started from the Bottom", "Drake"),
    ("In My Feelings", "Drake"),
    ("99 Problems", "Jay-Z"),
    ("Empire State of Mind", "Jay-Z"),
    ("IZZO (H.O.V.A.)", "Jay-Z"),
    ("Hard Knock Life", "Jay-Z"),
    ("Big Pimpin'", "Jay-Z"),
    ("Gold Digger", "Kanye West"),
    ("Stronger", "Kanye West"),
    ("All Falls Down", "Kanye West"),
    ("Jesus Walks", "Kanye West"),
    ("Runaway", "Kanye West"),
    ("Ms. Jackson", "Outkast"),
    ("Hey Ya!", "Outkast"),
    ("B.O.B.", "Outkast"),
    ("The Way I Am", "Eminem"),
    ("Nuthin' But a G Thang", "Dr. Dre"),
    ("Still D.R.E.", "Dr. Dre"),
    ("California Love", "2Pac"),
    ("Changes", "2Pac"),
    ("Dear Mama", "2Pac"),
    ("Juicy", "The Notorious B.I.G."),
    ("Hypnotize", "The Notorious B.I.G."),
    ("Big Poppa", "The Notorious B.I.G."),
    ("Waterfalls", "TLC"),
    ("No Scrubs", "TLC"),
    ("Creep", "TLC"),
    ("Old Town Road", "Lil Nas X"),
    ("MONTERO", "Lil Nas X"),
    ("Sicko Mode", "Travis Scott"),
    ("Goosebumps", "Travis Scott"),
    ("XO Tour Llif3", "Lil Uzi Vert"),
    ("Rockstar", "Post Malone"),
    ("Sunflower", "Post Malone"),
    ("Circles", "Post Malone"),
    # ── Folk / Americana / Country ────────────────────────────────────────────
    ("Like a Rolling Stone", "Bob Dylan"),
    ("Mr. Tambourine Man", "Bob Dylan"),
    ("Blowin' in the Wind", "Bob Dylan"),
    ("The Times They Are a-Changin'", "Bob Dylan"),
    ("Tangled Up in Blue", "Bob Dylan"),
    ("Jolene", "Dolly Parton"),
    ("I Will Always Love You", "Dolly Parton"),
    ("9 to 5", "Dolly Parton"),
    ("Ring of Fire", "Johnny Cash"),
    ("Man in Black", "Johnny Cash"),
    ("Hurt", "Johnny Cash"),
    ("Folsom Prison Blues", "Johnny Cash"),
    ("Fast Car", "Tracy Chapman"),
    ("Talkin' 'Bout a Revolution", "Tracy Chapman"),
    ("The Sound of Silence", "Simon & Garfunkel"),
    ("Mrs. Robinson", "Simon & Garfunkel"),
    ("Bridge Over Troubled Water", "Simon & Garfunkel"),
    ("The Boxer", "Simon & Garfunkel"),
    ("Fire and Rain", "James Taylor"),
    ("Carolina in My Mind", "James Taylor"),
    ("Woodstock", "Joni Mitchell"),
    ("Big Yellow Taxi", "Joni Mitchell"),
    ("Both Sides Now", "Joni Mitchell"),
    ("Take Me Home Country Roads", "John Denver"),
    ("Leaving on a Jet Plane", "John Denver"),
    ("Rocky Mountain High", "John Denver"),
    ("Wagon Wheel", "Old Crow Medicine Show"),
    ("Tennessee Whiskey", "Chris Stapleton"),
    ("Whiskey in a Jar", "Thin Lizzy"),
    ("Country Roads", "Toots and the Maytals"),
    # ── Electronic / Dance ────────────────────────────────────────────────────
    ("Around the World", "Daft Punk"),
    ("Get Lucky", "Daft Punk"),
    ("One More Time", "Daft Punk"),
    ("Harder Better Faster Stronger", "Daft Punk"),
    ("Da Funk", "Daft Punk"),
    ("Blue (Da Ba Dee)", "Eiffel 65"),
    ("Sandstorm", "Darude"),
    ("Levels", "Avicii"),
    ("Wake Me Up", "Avicii"),
    ("Hey Brother", "Avicii"),
    ("Don't You Worry Child", "Swedish House Mafia"),
    ("One", "Swedish House Mafia"),
    ("Titanium", "David Guetta"),
    ("Without You", "David Guetta"),
    ("Happy", "Pharrell Williams"),
    ("Uptown Funk", "Mark Ronson"),
    ("Can't Stop the Feeling!", "Justin Timberlake"),
    ("SexyBack", "Justin Timberlake"),
    ("Mirrors", "Justin Timberlake"),
    ("Cry Me a River", "Justin Timberlake"),
    ("Sweet Dreams", "Eurythmics"),
    ("Here Comes the Rain Again", "Eurythmics"),
    ("Girls Just Want to Have Fun", "Cyndi Lauper"),
    ("Time After Time", "Cyndi Lauper"),
    ("Take On Me", "A-ha"),
    ("West End Girls", "Pet Shop Boys"),
    ("It's a Sin", "Pet Shop Boys"),
    ("Blue Monday", "New Order"),
    ("True Faith", "New Order"),
    ("Personal Jesus", "Depeche Mode"),
    ("Enjoy the Silence", "Depeche Mode"),
    ("Just Can't Get Enough", "Depeche Mode"),
    ("Tainted Love", "Soft Cell"),
    ("Pure Shores", "All Saints"),
    # ── R&B / Neo-Soul ────────────────────────────────────────────────────────
    ("No Ordinary Love", "Sade"),
    ("Smooth Operator", "Sade"),
    ("The Sweetest Taboo", "Sade"),
    ("Killing Me Softly", "Fugees"),
    ("Ready or Not", "Fugees"),
    ("Ex-Factor", "Lauryn Hill"),
    ("Doo Wop (That Thing)", "Lauryn Hill"),
    ("On & On", "Erykah Badu"),
    ("Bag Lady", "Erykah Badu"),
    ("Back to Life", "Soul II Soul"),
    ("Fantasy", "Mariah Carey"),
    ("Hero", "Mariah Carey"),
    ("We Belong Together", "Mariah Carey"),
    ("Always Be My Baby", "Mariah Carey"),
    ("I Will Always Love You", "Whitney Houston"),
    ("Greatest Love of All", "Whitney Houston"),
    ("I Wanna Dance with Somebody", "Whitney Houston"),
    ("And I Am Telling You", "Jennifer Holliday"),
    ("Unpretty", "TLC"),
    ("No Scrubs", "TLC"),
    ("Say My Name", "Destiny's Child"),
    ("Survivor", "Destiny's Child"),
    ("Bootylicious", "Destiny's Child"),
    ("Beautiful", "Christina Aguilera"),
    ("Fighter", "Christina Aguilera"),
    ("Genie in a Bottle", "Christina Aguilera"),
    ("Toxic", "Britney Spears"),
    ("Baby One More Time", "Britney Spears"),
    ("Oops!... I Did It Again", "Britney Spears"),
    # ── Jazz / Blues ──────────────────────────────────────────────────────────
    ("What a Wonderful World", "Louis Armstrong"),
    ("La Vie en Rose", "Louis Armstrong"),
    ("Take Five", "Dave Brubeck"),
    ("So What", "Miles Davis"),
    ("Round Midnight", "Thelonious Monk"),
    ("Blue in Green", "Miles Davis"),
    ("A Foggy Day", "Frank Sinatra"),
    ("New York New York", "Frank Sinatra"),
    ("Fly Me to the Moon", "Frank Sinatra"),
    ("My Way", "Frank Sinatra"),
    ("Come Fly with Me", "Frank Sinatra"),
    ("The Girl from Ipanema", "Astrud Gilberto"),
    ("Summertime", "Billie Holiday"),
    ("Strange Fruit", "Billie Holiday"),
    ("God Bless the Child", "Billie Holiday"),
    ("At Last", "Etta James"),
    ("I'd Rather Go Blind", "Etta James"),
    ("Hound Dog", "Elvis Presley"),
    ("Jailhouse Rock", "Elvis Presley"),
    ("Love Me Tender", "Elvis Presley"),
    ("Suspicious Minds", "Elvis Presley"),
    ("Sweet Home Chicago", "Robert Johnson"),
    ("Cross Road Blues", "Robert Johnson"),
    ("The Thrill Is Gone", "B.B. King"),
    ("Sweet Little Angel", "B.B. King"),
    # ── Indie / Alternative ───────────────────────────────────────────────────
    ("Wonderwall", "Oasis"),
    ("Champagne Supernova", "Oasis"),
    ("Don't Look Back in Anger", "Oasis"),
    ("Karma Police", "Radiohead"),
    ("Creep", "Radiohead"),
    ("Fake Plastic Trees", "Radiohead"),
    ("High and Dry", "Radiohead"),
    ("Bittersweet Symphony", "The Verve"),
    ("Bitter Sweet Symphony", "The Verve"),
    ("Losing My Religion", "R.E.M."),
    ("Everybody Hurts", "R.E.M."),
    ("Man on the Moon", "R.E.M."),
    ("Smells Like Teen Spirit", "Nirvana"),
    ("Come as You Are", "Nirvana"),
    ("Heart-Shaped Box", "Nirvana"),
    ("Black Hole Sun", "Soundgarden"),
    ("Spoonman", "Soundgarden"),
    ("Under the Bridge", "Red Hot Chili Peppers"),
    ("Californication", "Red Hot Chili Peppers"),
    ("Scar Tissue", "Red Hot Chili Peppers"),
    ("Black", "Pearl Jam"),
    ("Jeremy", "Pearl Jam"),
    ("Even Flow", "Pearl Jam"),
    ("Semi-Charmed Life", "Third Eye Blind"),
    ("Jumper", "Third Eye Blind"),
    ("1979", "The Smashing Pumpkins"),
    ("Bullet with Butterfly Wings", "The Smashing Pumpkins"),
    ("Today", "The Smashing Pumpkins"),
    ("Self Esteem", "The Offspring"),
    ("Come Out and Play", "The Offspring"),
    ("All the Small Things", "blink-182"),
    ("What's My Age Again?", "blink-182"),
    ("The Middle", "Jimmy Eat World"),
    ("Sweetness", "Jimmy Eat World"),
    ("Mr. Brightside", "The Killers"),
    ("Somebody Told Me", "The Killers"),
    ("Glamorous Indie Rock & Roll", "The Killers"),
    ("Take Me Out", "Franz Ferdinand"),
    ("Do You Want To", "Franz Ferdinand"),
    ("Seven Nation Army", "The White Stripes"),
    ("Icky Thump", "The White Stripes"),
    ("Fell in Love with a Girl", "The White Stripes"),
    ("Maps", "Yeah Yeah Yeahs"),
    ("Heads Will Roll", "Yeah Yeah Yeahs"),
    ("Dog Days Are Over", "Florence and the Machine"),
    ("Shake It Out", "Florence and the Machine"),
    ("You Got the Love", "Florence and the Machine"),
    ("Clocks", "Coldplay"),
    ("The Scientist", "Coldplay"),
    ("Yellow", "Coldplay"),
    ("Fix You", "Coldplay"),
    ("Viva la Vida", "Coldplay"),
    ("Amsterdam", "Coldplay"),
    # ── Reggae ────────────────────────────────────────────────────────────────
    ("No Woman No Cry", "Bob Marley"),
    ("Redemption Song", "Bob Marley"),
    ("One Love", "Bob Marley"),
    ("Three Little Birds", "Bob Marley"),
    ("Get Up Stand Up", "Bob Marley"),
    ("Jamming", "Bob Marley"),
    ("Stir It Up", "Bob Marley"),
    ("Pressure Drop", "Toots and the Maytals"),
    ("Rivers of Babylon", "The Melodians"),
    ("Red Red Wine", "UB40"),
    # ── 2010s Pop / R&B ───────────────────────────────────────────────────────
    ("Royals", "Lorde"),
    ("Yellow Flicker Beat", "Lorde"),
    ("Team", "Lorde"),
    ("Chandelier", "Sia"),
    ("Elastic Heart", "Sia"),
    ("Cheap Thrills", "Sia"),
    ("Breathe Me", "Sia"),
    ("Fancy", "Iggy Azalea"),
    ("Anaconda", "Nicki Minaj"),
    ("Super Bass", "Nicki Minaj"),
    ("Starships", "Nicki Minaj"),
    ("Bang Bang", "Jessie J"),
    ("Price Tag", "Jessie J"),
    ("Titanium", "David Guetta"),
    ("Moves Like Jagger", "Maroon 5"),
    ("Sugar", "Maroon 5"),
    ("She Will Be Loved", "Maroon 5"),
    ("Payphone", "Maroon 5"),
    ("Animals", "Maroon 5"),
    ("Despacito", "Luis Fonsi"),
    ("Con Calma", "Daddy Yankee"),
    ("Lean On", "Major Lazer"),
    ("Latch", "Disclosure"),
    ("Riptide", "Vance Joy"),
    ("Budapest", "George Ezra"),
    ("Barcelona", "George Ezra"),
    ("Want to Want Me", "Jason Derulo"),
    ("Talk Dirty", "Jason Derulo"),
    ("Wiggle", "Jason Derulo"),
    # ── Metal / Hard Rock ─────────────────────────────────────────────────────
    ("Master of Puppets", "Metallica"),
    ("One", "Metallica"),
    ("Enter Sandman", "Metallica"),
    ("Nothing Else Matters", "Metallica"),
    ("Fade to Black", "Metallica"),
    ("Paranoid", "Black Sabbath"),
    ("Iron Man", "Black Sabbath"),
    ("War Pigs", "Black Sabbath"),
    ("Crazy Train", "Ozzy Osbourne"),
    ("Mr. Crowley", "Ozzy Osbourne"),
    ("Running with the Devil", "Van Halen"),
    ("Panama", "Van Halen"),
    ("Eruption", "Van Halen"),
    ("Welcome to the Jungle", "Guns N' Roses"),
    ("November Rain", "Guns N' Roses"),
    ("Paradise City", "Guns N' Roses"),
    ("Highway to Hell", "AC/DC"),
    ("Thunderstruck", "AC/DC"),
    ("You Shook Me All Night Long", "AC/DC"),
    ("Hell's Bells", "AC/DC"),
    ("Breaking the Law", "Judas Priest"),
    ("Living After Midnight", "Judas Priest"),
    ("The Trooper", "Iron Maiden"),
    ("Run to the Hills", "Iron Maiden"),
    ("Number of the Beast", "Iron Maiden"),
    # ── Classical crossover ───────────────────────────────────────────────────
    ("Clair de Lune", "Claude Debussy"),
    ("Fur Elise", "Ludwig van Beethoven"),
    ("Moonlight Sonata", "Ludwig van Beethoven"),
    ("Nessun Dorma", "Luciano Pavarotti"),
    ("O Sole Mio", "Enrico Caruso"),
]

# Deduplicate
_seen: set = set()
_deduped = []
for _item in TOP_500:
    _k = (_item[0].lower(), _item[1].lower())
    if _k not in _seen:
        _seen.add(_k)
        _deduped.append(_item)
TOP_500 = _deduped

# Keep TOP_100 alias for any code that still imports it
TOP_100 = TOP_500[:100]
